config/routes.rb
Rails.application.routes.draw do
  resources :games, only: [:index, :new, :create, :show] do
    resources :claim_route, only: [:new, :create]
    resources :draw_train_cars, only: [:create]
    resources :finish_turn, only: [:create]
  end
  match "/games/:id/board" => "games#board", via: :get

  root 'games#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  validates :name, presence: true
  has_many :where_city_1, foreign_key: :city1_id, class_name: 'Route'
  has_many :where_city_2, foreign_key: :city2_id, class_name: 'Route'

  def routes
    fields_to_include = [:route_type, :city1, :city2]
    where_city_1.includes(fields_to_include) + where_city_2.includes(fields_to_include)
  end

  def destinations
    routes.map do |route|
      route.alternate_city(self)
    end
  end
end

app/models/dealt_train_car.rb
class DealtTrainCar < ApplicationRecord
  belongs_to :player
  belongs_to :train_car_type
  validates :player, presence: true
  validates :train_car_type, presence: true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :players, dependent: :destroy
  has_many :dealt_train_cars, through: :players
  has_many :route_claims, through: :players
  belongs_to :current_player, class_name: 'Player'

  validates :current_player, presence: true
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :game
  has_many :dealt_train_cars, dependent: :destroy
  has_many :route_claim

  validates :name, presence: true
  validates :colour, presence: true, uniqueness: { scope: :game }
  validates :game, presence: true
  validates :score, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
  validates :train_pieces, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
end

app/models/route.rb
class Route < ApplicationRecord
  belongs_to :city1, class_name: 'City'
  belongs_to :city2, class_name: 'City'
  belongs_to :route_type
  has_many :route_claims

  validates :pieces, presence: true,
    :numericality => { :greater_than => 0,
                       :less_than_or_equal_to => 6
                     }

  validates :svg_id, presence: true, uniqueness: true

  validate :cities_ordered_correctly

  # TODO: This is killing speed. Turn this into an association.
  def claimed_route_for_game(game)
    route_claims.joins(:player).merge(game.players).first
  end

  def cities_ordered_correctly
    return if (!city1 || !city2)

    if !city1.id || !city2.id
      errors.add(:base, 'Both cities must have IDs.')
    elsif city1.id == city2.id
      errors.add(:base, 'Both cities must be different.')
    elsif city1.id > city2.id
      errors.add(:base, 'city1 must have a lower index than city2')
    end
  end

  def alternate_city(compare_city)
    if city1 == compare_city
      city2
    elsif city2 == compare_city
      city1
    end
  end
end

app/models/route_claim.rb
class RouteClaim < ApplicationRecord
  belongs_to :player
  belongs_to :route
  has_one :game, through: :player
end

app/models/route_type.rb
class RouteType < ApplicationRecord
  validates :colour, presence: true
end

app/models/train_car_type.rb
class TrainCarType < ApplicationRecord
  has_many :dealt_train_car
  validates :name, presence: true
  validates :total, presence: true
  validates :colour, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/claim_route_controller.rb
class ClaimRouteController < ApplicationController
  ERROR_PREFIX = "Claim route: "

  def new
    @route = route_param
    @game = game_param
    @player = @game.current_player
  end

  def create
    game = game_param

    service = ClaimRoute.new(player: game.current_player, train_cars: dealt_train_cars, route: route_param)
    if !service.call
      flash[:errors] = service.errors.map { |error_message| "#{ERROR_PREFIX}#{error_message}" }
    end
    redirect_to game
  end

  private

  def game_param
    Game.find(params.require(:game_id))
  end

  def route_param
    Route.find(params.require(:route_id))
  end

  def dealt_train_cars
    train_car_ids = params[:dealt_train_car_ids] || []
    train_car_ids.map { |train_car_id| DealtTrainCar.find(train_car_id) }
  end
end

app/controllers/draw_train_cars_controller.rb
class DrawTrainCarsController < ApplicationController
  DRAW_TRAIN_CARS_FAILED_ERROR = "Could not draw train cars."

  def create
    @game = Game.find(params.require(:game_id))
    @player = @game.current_player

    draw_train_cars_result = MakeDrawTrainCarsTurn.new(player: @player).call
    if !draw_train_cars_result
      flash[:errors] = [DRAW_TRAIN_CARS_FAILED_ERROR]
    end
    redirect_to @game
  end
end

app/controllers/finish_turn_controller.rb
class FinishTurnController < ApplicationController
  FINISH_TURN_FAILED_ERROR = "Could not finish turn."

  def create
    @game = Game.find(params.require(:game_id))

    finish_turn_result = FinishTurn.new(game: @game).call
    if !finish_turn_result
      flash[:errors] = [FINISH_TURN_FAILED_ERROR]
    end
    redirect_to @game
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params.require(:id))
    @player = @game.current_player

    @all_city_destinations = FetchAllCityDestinations.new(game: @game).call
  end

  def new
    @game = Game.new
    @player_count = 5
  end

  def create
    setup_game = SetupGame.new(player_details: player_details)

    if setup_game.call
      redirect_to setup_game.game
    elsif
      flash[:errors] = setup_game.errors
      redirect_to :new_game
    end
  end

  def destroy
    @game.destroy
    redirect_to games_url, notice: 'Game was successfully destroyed.'
  end

  def board
    @game = Game.find(params.require(:id))

    board = Route.all.map do |route|
      board_display = {
        svgId: route.svg_id,
        routeId: route.id
      }

      route_claim = route.claimed_route_for_game(@game)
      board_display['isFilled'] = route_claim.present?
      board_display['canClick'] = !@game.finished_action && !route_claim.present?

      if route_claim.present?
        board_display['displayColour'] = route_claim.player.colour
      end

      board_display
    end

    respond_to do |format|
      format.json { render :json => board }
    end
  end

  private

  def clean_player_detail(player_detail)
    player_detail.transform_keys do |detail_key|
      detail_key.to_sym
    end
  end

  def player_details
    player_params = params.fetch(:game)['players'].to_unsafe_h # TODO: Any way to do this safely?
    player_params.transform_values { |player_detail| clean_player_detail(player_detail) }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/claim_route/new.html.erb
<% content_for :title, "Claim a route" %>

<h1>Claim a Route</h1>

<%= tag "div", :data => {:routeSVGId => @route.svg_id}, :class => "route-preview board" %>
<%= render 'games/board' %>
<br>

<div class="row">
  <div class="col-sm-4 col-md-2">
    <div class="details small">From:</div>
    <div class="details large"><%= @route.city1.name %></div>
  </div>
  <div class="col-sm-4 col-md-2">
    <div class="details small">To:</div>
    <div class="details large"><%= @route.city2.name %></div>
  </div>
  <div class="col-sm-4 col-md-2">
    <div class="details small">Pieces:</div>
    <div class="details large"><%= @route.pieces %></div>
  </div>
  <div class="col-sm-4 col-md-2">
    <div class="details small">Colour:</div>
    <div class="details large"><%= @route.route_type.colour %></div>
  </div>
</div>

<h3>Pieces to Use</h3>
<%= form_tag game_claim_route_index_path(@game) do |f| %>
  <div class="pieces">
    <%= hidden_field_tag :route_id, @route.id %>
    <% @player.dealt_train_cars.each do |dealt_train_car| %>
      <div class="checkable dealt-train-car">
        <label class="btn">
          <%= image_tag "cards/" + dealt_train_car.train_car_type.name + ".jpg", class: "img-check" %>
          <%= check_box_tag "dealt_train_car_ids[]", dealt_train_car.id, false, class: "hidden" %>
        </label>
      </div>
    <% end %>
  </div>

  <div class="clear">
    <%= link_to "Back", @game, class: "btn btn-default" %>
    <%= submit_tag "Claim Route", class: "btn btn-primary" %>
  </div>
  <br>
<% end %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<div class="row">
  <% @games.each do |game| %>
    <div class="col-sm-6">
      <div class="panel panel-default">
        <div class="panel-body">
          <p>
            <strong>Players</strong>
            <table style="width: 100%">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Colour</th>
                  <th>Score</th>
                  <th>Train Pieces</th>
                  <th>Dealt Train Cars</th>
                  <th>Is current player?</th>
                </tr>
              </thead>
              <tbody>
                <% game.players.each do |player| %>
                  <tr>
                    <td><%= player.name %></td>
                    <td><%= player.colour %></td>
                    <td><%= player.score %></td>
                    <td><%= player.train_pieces %></td>
                    <td><%= player.dealt_train_cars.count %></td>
                    <td><%= player == game.current_player ? "Yes" : "" %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </p>

          <%= link_to 'Show Game', game, class: "btn btn-primary" %>
          <%= link_to 'Destroy Game', game, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/games/new.html.erb
<% content_for :title, "New Game" %>

<div class="new-game">
  <h2>New Game</h2>

  <%= bootstrap_form_for @game do |f| %>
    <% if flash[:errors] %>
      <% game_errors = flash[:errors]["game"] %>
    <% end %>
    <% if game_errors %>
      <% game_errors.each do |game_error| %>
        <div class="alert alert-danger" role="alert">
          <%= game_error %>
        </div>
      <% end %>
    <% end %>

    <div class="row">
      <% @player_count.times do |index| %>
        <%=f.fields_for "players" do |players_fields| %>
          <%=players_fields.fields_for "player_#{index}" do |player_fields| %>
            <div class="col-sm-6 col-md-4">
              <div class="panel panel-default">
                <div class="panel-body">
                  <h4><%= "Player #{index + 1}" %></h4>
                  <% if flash[:errors] %>
                    <% field_errors = flash[:errors]["player_#{index}"] %>
                  <% end %>
                  <% if field_errors %>
                    <%field_errors.each do |field_error| %>
                      <div class="alert alert-danger" role="alert">
                        <%= field_error %>
                      </div>
                    <% end %>
                  <% end %>
                  <%= player_fields.text_field :name %>
                  <%= player_fields.select :colour, ["Yellow", "Black", "Blue", "Green", "Red"] %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>

    <div class="btn-group">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/games/show.html.erb
<% content_for :title, "Game" %>

<p id="notice"><%= notice %></p>

<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <div class="alert alert-danger" role="alert">
      <%= error %>
    </div>
  <% end %>
  <br>
<% end %>

<div class="row">
  <div class="col-sm-4 col-md-2">
    <div class="details small">Name:</div>
    <div class="details large"><%= @player.name %></div>
  </div>

  <div class="col-sm-4 col-md-2">
    <div class="details small">Colour:</div>
    <div class="details large"><%= @player.colour %></div>
  </div>

  <div class="col-sm-4 col-md-2">
    <div class="details small">Train Pieces:</div>
    <div class="details large"><%= @player.train_pieces %></div>
  </div>

  <div class="col-sm-4 col-md-2">
    <div class="details small">Score:</div>
    <div class="details large"><%= @player.score %></div>
  </div>

  <div class="col-sm-4 col-md-2">
    <div class="game-action-buttons">
      <%= button_to 'Finish turn', game_finish_turn_index_path(@game), class: "btn btn-primary" if @game.finished_action %>
      <%= button_to 'Draw more train cards', game_draw_train_cars_path(@game), class: "btn btn-primary" if !@game.finished_action %>
    </div>
  </div>
</div>

<% @player.dealt_train_cars.each do |dealt_train_car| %>
  <div class="dealt-train-car">
    <%= image_tag("cards/" + dealt_train_car.train_car_type.name + ".jpg") %>
  </div>
<% end %>

<div class="interactive board">
  <%= render 'games/board' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Ticket to Ride</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="/" class="logo">
            <%= image_tag("logo.png") %>
          </a>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li>
              <a href="/games/new/">New Game</a>
            </li>
            <li>
              <a href="/games">Saved Games</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="main container">
      <%= yield %>
    </div>
  </body>
</html>